[package]
name = "xcolor"
version = "0.3.1"
description = "Lightweight color picker for X11"
authors = ["Samuel Laur√©n <samuel.lauren@iki.fi>"]
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["color", "utility", "color-picker", "x11"]
homepage = "https://github.com/Soft/xcolor"
repository = "https://github.com/Soft/xcolor"
build = "build.rs"
exclude = ["docker/*", "_config.yml"]

[dependencies]
failure = "0.1.1"
nom = "3.2.1"
clap = "2.31.2"
nix = "0.10.0"
libc = "0.2.39"

[dependencies.xcb]
version = "0.8.2"
features = ["shape"]

[build-dependencies]
clap = "2.31.2"

[profile.release]
lto = true
panic = "abort"

[badges]
travis-ci = { repository = "Soft/xcolor" }
