[package]
name = "xcolor"
version = "0.3.0"
description = "Lightweight color picker for X11"
authors = ["Samuel Laur√©n <samuel.lauren@iki.fi>"]
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["color", "utility", "color-picker", "x11"]
homepage = "https://github.com/Soft/xcolor"
repository = "https://github.com/Soft/xcolor"
exclude = ["docker/*", "_config.yml"]

[dependencies]
xcb = "0.8.2"
failure = "0.1.1"
nom = "3.2.1"
clap = "2.31.2"
nix = "0.10.0"

[profile.release]
lto = true
panic = "abort"

[badges]
travis-ci = { repository = "Soft/xcolor" }
